# Dockerfile for use by the continuous integration server (ci), in order to
# build and test the application.
#
# This Dockerfile provides the appropriate environment for building and testing
# the application. It should _not_ be used for creating Docker images for use
# in production.

FROM python:3.7-slim

RUN apt-get update && \
    apt-get install -y build-essential && \
    apt-get install -y git && \
    apt-get clean
