[project]
name = "plastron"
dynamic = ["version"]
authors = [
    { name='University of Maryland Libraries', email='lib-ssdr@umd.edu' },
    { name='Josh Westgard', email='westgard@umd.edu' },
    { name='Peter Eichman', email='peichman@umd.edu' },
    { name='Mohamed Abdul Rasheed', email='mohideen@umd.edu' },
    { name='Ben Wallberg', email='wallberg@umd.edu' },
    { name='David Steelman', email='dsteelma@umd.edu' },
    { name='Marc Andreu Grillo Aguilar', email='aguilarm@umd.edu' },
]
readme = "README.md"
requires-python = ">= 3.10"
dependencies = [
    "plastron-client",
    "plastron-jobs",
    "plastron-messaging",
    "plastron-models",
    "plastron-rdf",
    "plastron-repo",
    "plastron-utils",
]

[project.optional-dependencies]
cli = [ "plastron-cli" ]
stomp = [ "plastron-stomp" ]
web = [ "plastron-web" ]
test = [
    "plastron-cli[test]",
    "plastron-client[test]",
    "plastron-jobs[test]",
    "plastron-messaging[test]",
    "plastron-models[test]",
    "plastron-rdf[test]",
    "plastron-repo[test]",
    "plastron-stomp[test]",
    "plastron-utils[test]",
    "plastron-web[test]",
]

[build-system]
requires = ["setuptools>=66.1.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
# this is just a meta-package, and includes no code of its own
packages = []

[tool.setuptools.dynamic]
version = { "file" = "VERSION" }

[tool.uv.sources]
plastron-cli = { workspace = true }
plastron-client = { workspace = true }
plastron-jobs = { workspace = true }
plastron-messaging = { workspace = true }
plastron-models = { workspace = true }
plastron-rdf = { workspace = true }
plastron-repo = { workspace = true }
plastron-stomp = { workspace = true }
plastron-utils = { workspace = true }
plastron-web = { workspace = true }

[tool.uv.workspace]
members = ["plastron-*"]

[tool.pytest.ini_options]
# these warnings are coming from third-party code
filterwarnings = [
   'ignore:ConjunctiveGraph is deprecated:DeprecationWarning',
]

[tool.ruff.lint]
# for now, using the pre-0.16 default ruleset in ruff
# see https://astral.sh/blog/ruff-v0.16.0#better-default-rule-set
select = ["E4", "E7", "E9", "F"]
